### ISSUE TITLE
AVR_AVRDx portmacro.h UBaseType_t gives compile warning

### ISSUE THREAD

**Issue by danak6jq** [FreeRTOS/FreeRTOS-Kernel-Partner-Supported-Ports#4]
portmacro.h defines:

`typedef unsigned char    UBaseType_t;
`
which gives this compile warning:

`right shift count >= width of type [-Wshift-count-overflow]	RTOSDemo FreeRTOS\FreeRTOS\Demo\Common\Minimal\TaskNotify.c	719`

`    return( ( uxNextRand >> 16 ) & ( ( size_t ) 0x7fff ) );
`

**Comment by RichardBarry** [comment]
Thanks for the information - however this file is just a demo and test file - not part of the kernel port this ticket is open under.

**Comment by danak6jq** [comment]
Understood - I just found the relevant source and clicked "issues" and this is where I ended-up.
