### ISSUE TITLE
Does MPLAB file "AVR_Dx_MPLAB.X" exisit on github?

### ISSUE THREAD

**Issue by microPaul** [FreeRTOS/FreeRTOS-Kernel-Partner-Supported-Ports#6]
I'm very new to FreeRTOS and github,, so I'm coming at this as a newbee.

I'd like to try FreeRTOS on some AVR128DBxx development boards I've made and use MPLAB X IDE to do so.  I've done this on a Microchip Cortex MO board I made, but Microchip has made it maybe too easy to get up and running with their Harmony 3 configurator.

I've been going through the info on https://www.freertos.org/microchip-avr-dx-demo.html#FullDemo  and in it there is reference to a file "AVR_Dx_MPLAB.X", which sounds like it would be a prepackaged MPLAX project file that I assume includes the FreeRTOS kernal, the AVR-Dx specific portable files and the demo files themselves.

My problem is that I can't find "AVR_Dx_MPLAB.X" on github.  Am I reading the instructions on the https://www.freertos.org/microchip-avr-dx-demo.html#FullDemo page incorrectly?  Does such a file exist on github?

When I use MPLAB's "Add Existing Item" (the FreeRTOS kernal) into MPLab i just get a mess of files (.h and .c) without any organization.

I'd appreciate any guidance that might be offered.

**Comment by RichardBarry** [comment]
Grateful if you can copy your question [into the support forum](https://forums.freertos.org/) - where we will be happy to assist.  You can use your Github username and password to post there too.
